image: node:latest

types:
  - test

test_Schedules:
    type: test
    before_script:
        - apt-get update -qy
        - apt-get install -qq -o=Dpkg::Use-Pty=0 sqlite3
        - npm install --loglevel silent
    script:
        - npm test
