image: ubuntu:14.04

types:
  - test

test_Schedules:
    type: test
    before_script:
        - sudo apt-get update -qy
        - sudo apt-get install sqlite3
        - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | bash
        - nvm install node
        - npm install
    script:
        - npm test
