image: node:latest

types:
  - test

test_Schedules:
    type: test
    before_script:
        - sudo apt-get update -qy
        - sudo apt-get install sqlite3
        - npm install
    script:
        - npm test
