image: ubuntu:14.04

services:
  - sqlite3:latest

types:
  - test

test_Schedules:
    type: test
    before_script:
        - apt-get update -qy
        - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | bash
        - nvm install node
        - npm install
    script:
        - npm test
