/*
 * Schedules by Student Run Computing and Technology
 *
 * routes/index.js
 *
 * This routing file describes the main front end's routing.
 *
 * Serves as the root page as well as parsing the preset url's generated by the
 * application.
 */

var express = require('express')
var router = express.Router()
var config = require('config')

// Load site wide configurations
var siteInfo = config.get('general')

/* GET home page. */
router.get('/', function (req, res, next) {
  res.render('index', { siteInfo })
})

module.exports = router
