////////////////////////////////////////////////////////////////////////////////
//                 Mason SRCT: Schedules Main App Routes
// - This routing file describes the main front-end's routing.
// - This serves the root page as well as parses preset url's generated by the
//   application
////////////////////////////////////////////////////////////////////////////////
var express = require('express');
var router = express.Router();
var config = require('config');
var db = require('models');

// Load site wide configurations
var siteInfo = config.get('general');

/* GET home page. */
router.get('/', function(req, res, next) {
  res.render('index', { siteInfo });
})

module.exports = router;
