////////////////////////////////////////////////////////////////////////////////
//                 Mason SRCT: Schedules Main App Routes
// - This routing file describes the main front-end's routing.
// - This serves the root page as well as parses preset url's generated by the
//   application
////////////////////////////////////////////////////////////////////////////////
var express = require('express');
var router = express.Router();

// Load site wide configurations
var config = require('../config');

/* GET home page. */
router.get('/', function(req, res, next) {
  res.render('index', { config });
})

module.exports = router;
