# General Application Settings

general :
    name        : "Schedules"
    description : >
        "A simple application to add your class schedules
        to calendar applications, like your phone."

    organization :
        name        : "Mason SRCT"
        description : >
            "Student Run Computing and Technology"
        website     : "srct.gmu.edu"
        websiteURL  : "https://srct.gmu.edu"

# Sequelize Settings (Database)

sequelize :
    dialect : "sqlite"
    storage : "./.devDB/schedules.sqlite"

# Data Sources etc

schools :
    - slug      : GMU
      name      : George Mason University
      website   : www2.gmu.edu
      semesters :
          - slug     : "GMU2016SP"
            longName : "Spring 2016"
            dataFile : "GMU2016SP.min.json"

          - slug     : "GMU2016S"
            longName : "Summer 2016"
            dataFile : "GMU2016S.min.json"

          - slug     : "GMU2016F"
            longName : "Fall 2016"
            dataFile : "GMU2016F.min.json"

          - slug     : "GMU2017SP"
            longName : "Spring 2017"
            dataFile : "GMU2017SP.min.json"

schoolSlugs :
    - "GMU"
    - "VT"
